ecomapp/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("review/", SendReview.as_view(), name="review"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
     path("all-book/", BookProductsView.as_view(), name="allbook"),
     path("all-electronic/", ElectronicProductsView.as_view(), name="allelectronic"),
     path("all-clothes/", ClothesProductsView.as_view(), name="allclothes"),
     path("all-book/", BookProductsView.as_view(), name="allbook"),
     path("all-electronic/", ElectronicProductsView.as_view(), name="allelectronic"),
     path("all-clothes/", ClothesProductsView.as_view(), name="allclothes"),
    path("update-wishlist-<int:pro_id>/", UpdateToWishList.as_view(), name="updateWishList"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("wishlist/", WishListView.as_view(), name="wishlist"),
    path("reviewlist/", ReviewListView.as_view(), name="reviewlist"),
    path("review-success/", ReviewSuccessView.as_view(), name="reviewsuccess"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),
    path("edit-profile/<int:usr_id>/", EditProfileView.as_view(), name="editprofile"),
    path("shipping-address/<int:cus_id>/", ShippingAddressListView.as_view(), name="shippingaddresslist"),
    path("shipping-address/create/<int:cus_id>/", ShippingAddressCreateView.as_view(), name="shippingaddresscreate"),
    path("shipping-address/edit/<int:cus_id>/<int:addr_id>/", ShippingAddressEditView.as_view(), name="shippingaddressedit"),
    path("shipping-address/delete/<int:cus_id>/<int:addr_id>/", ShippingAddressDeleteView.as_view(), name="shippingaddressdelete"),
    

#     path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
#     path("password-reset/<email>/<token>/",
#          PasswordResetView.as_view(), name="passwordreset"),
#     # Admin Side pages
    path("admin-logout/", AdminLogoutView.as_view(), name="adminlogout"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-review/", AdminReviewListView.as_view(), name="adminreviewlist"),
    path("admin-review/<int:pk>/", AdminReviewDetailView.as_view(),
         name="adminreviewdetail"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-reply/", AdminReplyReviewView.as_view(), name="adminreplyreview"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

     path("admin-staff/list/", AdminStaffListView.as_view(), name="adminstafflist"),
     path("admin-staff/add/", AdminStaffCreateView.as_view(), name="adminstaffcreate"),
     path("admin-staff-detail/<int:staff_id>/", AdminStaffDetailView.as_view(), name="adminstaffdetail"),

    path("admin-product-detail/<int:pro_id>/", AdminProductDetailView.as_view(), name="adminproductdetail"),
    path("admin-item-detail/<slug:slug>/", AdminItemDetailView.as_view(), name="adminitemdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),
     path("admin-pending-orders/", AdminPendingOrder.as_view(), name="adminpendingorders"),
    path("admin-order-<int:pk>-change/",
         AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
     path("admin-item/list/", AdminItemListView.as_view(),
         name="adminitemlist"),
     path("admin-importingrecord/list/", AdminImprotingrecordListView.as_view(),
         name="adminimportingrecordlist"),
     path("admin-product/delete-<int:pro_id>", AdminProductDeleteView.as_view(),
         name="adminproductdelete"),
#     path("admin-product/add/", AdminProductCreateView.as_view(),
#          name="adminproductcreate"),
     path("admin-product/add/<int:cate_id>/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),

    path("admin-product/import/", AdminImportProductView.as_view(),
         name="adminimportproduct"),
    path("statistic", Statistic.as_view(),
         name="statistic"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>

<body style="background-color: #fff">
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #D19C97">
        <a class="navbar-brand" href="{% url 'ecomapp:adminhome' %}">BANANA</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if request.user.account %}
                    {% if request.user.account.users.staffs.position == "Manager" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminpendingorders' %}">Pending Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminorderlist' %}">All Orders</a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminproductlist' %}">All Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminitemlist' %}">All Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminimportproduct' %}">Import Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminreviewlist' %}">All Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:home' %}" target="_blank">Visit site</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminstafflist' %}">All Staff</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:statistic' %}">View Stats</a>
                        </li>
                    {% endif%}
                    {% if request.user.account.users.staffs.position == "Warehouse Staff" %}
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminproductlist' %}">All Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminitemlist' %}">All Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminimportproduct' %}">Import Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:home' %}" target="_blank">Visit site</a>
                        </li>
                    {% endif%}
                    {% if request.user.account.users.staffs.position == "Sale Staff" %} 
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminpendingorders' %}">Pending Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminreviewlist' %}">All Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminorderlist' %}">All Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:home' %}" target="_blank">Visit site</a>
                        </li>
                    {% endif%}
                
                    {% if request.user.account.users.staffs.position == "Business Staff" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:adminitemlist' %}">All Items</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'ecomapp:home' %}" target="_blank">Visit site</a>
                        </li>
                    {% endif%}
                         <li class="nav-item">
                            <a class="nav-item nav-link" href="{% url 'ecomapp:adminlogout' %}">Đăng xuất</a>
                         </li>
                {% else %}
                  <li class="nav-item">
                       <P>  </p>
                  </li>
                {% endif%} 
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:adminorderlist' %}">All Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:adminproductlist' %}">All Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:adminitemlist' %}">All Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:adminimportproduct' %}">Import Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:adminreviewlist' %}">All Reviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:home' %}" target="_blank">Visit site</a>
                </li> {% endcomment %}
            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

templates/adminpages/adminhome.html
{% extends "adminpages/adminbase.html" %}

{% block title %}Admin Home{% endblock %}

{% block content %}
<br>
<h1>Admin Honme</h1>
{% endblock %}

templates/adminpages/adminimportproduct.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Import Product{% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Warehouse Staff" %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 mx-auto">
                <h3>Import product</h3>
                <a href = "{% url 'ecomapp:adminimportingrecordlist' %}">Xem Danh Sách Hoá Đơn</a>
                <hr>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-info">Submit Data</button>
                </form>
            </div>
        </div>
    </div>
    {% else %} 
            <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminitemdetail.html
{% extends "adminpages/adminbase.html" %}

{% block title %}{{product.productid.name}}{% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Business Staff" %}
    <div class="container">
        <h3>Sản phẩm: {{product.productid.name}}</h3>
        <hr>
        <div class="row">
            <div class="col-md-4">
                <img src="{{product.image.url}}" alt="" class="img-fluid">
                <div class="row">
                    {% for pi in product.productimage_set.all %}
                    <div class="col-md-4 p-3">
                        <a href="{{pi.image.url}}" target="_blank">
                            <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;"
                                alt="">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-8">
                <h4>{{product.productid.name}}</h4>
                <h5>Danh mục: {{product.productid.category}}</h5>
                <form action="{% url 'ecomapp:adminitemdetail' product.slug %}" method="POST">
                    {% csrf_token %}
                    <h5>Giá: {{form.price}}</h5>
                    <label> {{ form.description.label }}: </label>
                    <br>
                    {{ form.description }}
                    <hr>
                    <button class="btn btn-info"  type="submit" name = "upload" value = "true">Đăng Tải</button>
                    <button class="btn btn-info"  type="submit" name = "upload" value = "false">Ngừng Đăng Tải</button>
                </form>
            </div>
        </div>
    </div>
    {% else %} 
            <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminlogin.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Admin Login{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Admin</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}

{% block title %}Order Detail{% endblock  %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Sale Staff" %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h3>Order Detail</h3>
                <hr>
                <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
                <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.status}}</p>
                <p><span class="font-weight-bold">Order On: </span> {{ord_obj.time}}({{ord_obj.time|timesince}} ago)</p>
                <p><span class="font-weight-bold">Customer Information: </span>  {{ord_obj.customerid.userid.fullnameid.fullname}}, {{ord_obj.customerid.userid.contactinfoid.phonenumber}}</p>
                <p><span class="font-weight-bold">Shipping Address: </span> By {{ord_obj.shippingaddressid.addressid.address}} -({{ord_obj.shippingaddressid.phonenumberreceive}})</p>
                <p><span class="font-weight-bold">Payment Information: </span>  Using {{ord_obj.paymentid.method}} ({% if ord_obj.paymentid.isComplete %}Payment Completed{% else %}Not Paid{% endif %})</p>
                <h4>Ordered Items</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Item</th>
                            <th>Rate</th>
                            <th>Quantity</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ori in ord_obj.orderitem_set.all %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a target="_blank"
                                    href="{% url 'ecomapp:productdetail' ori.itemid.slug %}">{{ori.itemid.productid.name}}({{ori.itemid.id}})</a>
                            </td>
                            <td>{{ori.itemid.price}}</td>
                            <td>{{ori.count}}</td>
                            <td>{{ori.subTotal}}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <th colspan="4" class="text-right">Subtotal: </th>
                            <th>{{ord_obj.cost_all_items|intcomma}} VNĐ</th>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-right">Shipping cost: </th>
                            <th>{{ord_obj.cost_shipping|intcomma}} VNĐ</th>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-right">Total: </th>
                            <th>{{ord_obj.total|intcomma}} VNĐ</th>
                        </tr>
                    </tbody>
                </table>
                <form action="{% url 'ecomapp:adminorderstatuschange' ord_obj.id %}" method="POST">
                    {% csrf_token %}
                    <select name="status">
                        {% for i, j in allstatus %}
                        <option value="{{i}}" {% if i == ord_obj.status %}selected{% endif %}>{{j}}</option>
                        {% endfor %}
                    </select>
                    <button class="btn btn-info">Change</button>
                    
                </form>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminorderlist.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}All Orders {% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Sale Staff" %}
    <div class="container" style="padding-top: 3rem">
        <div class="row">
            <div class="col-md-12">
                <h3>All Orders</h3><hr>
                <table class="table table-hover">
                    <thead style="background-color: #D19C97">
                        <tr>
                            <th scope="col">STT</th>
                            <th scope="col">Order ID </th>
                            <th scope="col">Customer</th>
                            <th scope="col">Ordered On</th>
                            <th scope="col">Amount</th>
                            <th scope="col">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in allorders %}
                        <tr>
                            <td  scope="row">{{forloop.counter}}</td>
                            <td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                            <td>{{order.customerid.userid.fullnameid.fullname}}</td>
                            <td>{{order.time}}</td>
                            <td>{{order.total}}</td>
                            <td>{{order.status}}</td>
                
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminpendingorders.html
{% extends "adminpages/adminbase.html" %}

{% block title %}Pending Order{% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Sale Staff" %}
    <div class="container" style="padding-top: 3rem">
        <div class="row">
            <div class="col-md-12">
                <h3>Pending Orders</h3>
                <table class="table table-hover">
                    <thead style="background-color: #D19C97">
                        <tr>
                            <th scope="col">STT</th>
                            <th scope="col">Order ID </th>
                            <th scope="col">Customer</th>
                            <th scope="col">Ordered On</th>
                            <th scope="col">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in pendingorders %}
                        <tr>
                            <td scope="row">{{forloop.counter}}</td>
                            <td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                            <td>{{order.customerid.userid.fullnameid.fullname}}</td>
                            <td>{{order.time}}</td>
                            <td>{{order.total}}</td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminproductcreate.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Add New Product{% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Warehouse Staff" %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 mx-auto">
                <h3>Add New product</h3>
                <hr>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-info">Submit Data</button>
                </form>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminproductdetail.html
{% extends "adminpages/adminbase.html" %}

{% block title %}{{product.productid.name}}{% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Warehouse Staff" %}
    <div class="container">
        <h3>Product: {{product.name}}</h3>
        <h4>Category: {{product.type}}</h4>
        <hr>
        <div class="row">
            <div class="col-md-8">
                <form action="{% url 'ecomapp:adminproductdetail' product.id %}" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <hr>
                    <button class="btn btn-info"  type="submit" name = "upload" value = "true">Cập Nhật</button>
                </form>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%}
{% endblock %}

templates/adminpages/adminreplyreview.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Reply Review{% endblock %}

{% block content %}
{% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Sale Staff" %}
<div class="container">
    <h1 class="text-left">Phản Hồi ý Kiến Khách Hàng.</h1>
    <h5 class="text-left"></h1>
    <hr style="height:30px">
    <div>
        <form class="row g-3" action="{% url 'ecomapp:adminreplyreview' %}" method="POST">
            {% csrf_token %}
            <label class="col-12"> {{ form.content.label }}:</label>
            <div class="col-12">
              {{ form.content }}
            </div>
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Send</button>
            </div>
          </form>
    </div>
</div>
{% else %} 
      <p> Không có quyền truy cập </p> 
{% endif%} 
{% endblock %}

templates/adminpages/adminreviewdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}

{% block title %}Review Detail{% endblock  %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" or  request.user.account.users.staffs.position == "Sale Staff" %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h3>Review Detail</h3>
                <hr>
                <p><span class="font-weight-bold">Review ID: </span> #REVIEW_{{rv_obj.id}}</p>
                <p><span class="font-weight-bold">Review Status: </span> {{rv_obj.isReply}}</p>
                <p><span class="font-weight-bold">Create On: </span> {{rv_obj.reviewtime}}</p>
                <p><span class="font-weight-bold">Customer Information: </span> By {{rv_obj.customerid.userid.fullnameid.fullname}}, {{rv_obj.customerid.userid.contactinfoid.phonenumber}}</p>
                <p><span class="font-weight-bold">Content: </span> {{rv_obj.content}} </p>
                <p><span class="font-weight-bold">Sentiment : </span> {{rv_obj.sentiment}} </p>
                <form action="{% url 'ecomapp:adminreplyreview'  %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-info">Reply</button>
                </form>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%} 
{% endblock %}

templates/adminpages/adminstaffcreate.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Add New Staff{% endblock %}

{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" %}
        <div class="container">
            <div class="row">
                <div class="col-md-10 mx-auto">
                    <h3>Add New Staff</h3>
                    <hr>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-info">Submit Data</button>
                    </form>
                </div>
            </div>
        </div>
    {% else %} 
            <p> Không có quyền truy cập </p> 
    {% endif%} 
{% endblock %}

templates/adminpages/stafflist.html
{% extends "adminpages/adminbase.html" %}
{% block title %}All Staff{% endblock %}


{% block content %}
    {% if request.user.account.users.staffs.position == "Manager" %}
    <div class="container" style="padding-top: 3rem"> 
        <div class="row">
            <div class="col-md-12">
                <h3>All Staff list</h3><hr>
                <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:adminstafflist' %}" method="GET">
                    <button class="btn my-2 my-sm-0" type="submit" style="background-color: #cce6ff">Tìm kiếm</button>
                    <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search"
                        aria-label="Search" required>
                </form>
                <hr>
                <a href="{% url 'ecomapp:adminstaffcreate' %}">Add New Staff </a>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">STT</th>
                            <th scope="col">Code Staff</th>
                            <th scope="col">Position</th>
                            <th scope="col">Fullname</th>
                            <th scope="col">Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in allstaffs %}
                        <tr>
                            <td scope="row">{{forloop.counter}}</td>
                            <td><a href="{% url 'ecomapp:adminstaffdetail' p.userid.id %}">{{p.codeStaff}}</td>
                            <td>{{p.position}}</td>
                            <td>{{p.userid.fullnameid.fullname}}</td>
                            <td>{{p.userid.is_active}}</td>
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% else %} 
        <p> Không có quyền truy cập </p> 
    {% endif%} 
{% endblock %}