ecomapp/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("review/", SendReview.as_view(), name="review"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
     path("all-book/", BookProductsView.as_view(), name="allbook"),
     path("all-electronic/", ElectronicProductsView.as_view(), name="allelectronic"),
     path("all-clothes/", ClothesProductsView.as_view(), name="allclothes"),
     path("all-book/", BookProductsView.as_view(), name="allbook"),
     path("all-electronic/", ElectronicProductsView.as_view(), name="allelectronic"),
     path("all-clothes/", ClothesProductsView.as_view(), name="allclothes"),
    path("update-wishlist-<int:pro_id>/", UpdateToWishList.as_view(), name="updateWishList"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("wishlist/", WishListView.as_view(), name="wishlist"),
    path("reviewlist/", ReviewListView.as_view(), name="reviewlist"),
    path("review-success/", ReviewSuccessView.as_view(), name="reviewsuccess"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),
    path("edit-profile/<int:usr_id>/", EditProfileView.as_view(), name="editprofile"),
    path("shipping-address/<int:cus_id>/", ShippingAddressListView.as_view(), name="shippingaddresslist"),
    path("shipping-address/create/<int:cus_id>/", ShippingAddressCreateView.as_view(), name="shippingaddresscreate"),
    path("shipping-address/edit/<int:cus_id>/<int:addr_id>/", ShippingAddressEditView.as_view(), name="shippingaddressedit"),
    path("shipping-address/delete/<int:cus_id>/<int:addr_id>/", ShippingAddressDeleteView.as_view(), name="shippingaddressdelete"),
    

#     path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
#     path("password-reset/<email>/<token>/",
#          PasswordResetView.as_view(), name="passwordreset"),
#     # Admin Side pages
    path("admin-logout/", AdminLogoutView.as_view(), name="adminlogout"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-review/", AdminReviewListView.as_view(), name="adminreviewlist"),
    path("admin-review/<int:pk>/", AdminReviewDetailView.as_view(),
         name="adminreviewdetail"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-reply/", AdminReplyReviewView.as_view(), name="adminreplyreview"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

     path("admin-staff/list/", AdminStaffListView.as_view(), name="adminstafflist"),
     path("admin-staff/add/", AdminStaffCreateView.as_view(), name="adminstaffcreate"),
     path("admin-staff-detail/<int:staff_id>/", AdminStaffDetailView.as_view(), name="adminstaffdetail"),

    path("admin-product-detail/<int:pro_id>/", AdminProductDetailView.as_view(), name="adminproductdetail"),
    path("admin-item-detail/<slug:slug>/", AdminItemDetailView.as_view(), name="adminitemdetail"),
    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),
     path("admin-pending-orders/", AdminPendingOrder.as_view(), name="adminpendingorders"),
    path("admin-order-<int:pk>-change/",
         AdminOrderStatusChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
     path("admin-item/list/", AdminItemListView.as_view(),
         name="adminitemlist"),
     path("admin-importingrecord/list/", AdminImprotingrecordListView.as_view(),
         name="adminimportingrecordlist"),
     path("admin-product/delete-<int:pro_id>", AdminProductDeleteView.as_view(),
         name="adminproductdelete"),
#     path("admin-product/add/", AdminProductCreateView.as_view(),
#          name="adminproductcreate"),
     path("admin-product/add/<int:cate_id>/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),

    path("admin-product/import/", AdminImportProductView.as_view(),
         name="adminimportproduct"),
    path("statistic", Statistic.as_view(),
         name="statistic"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{%static 'css/ol.css' %}" rel="stylesheet">
    <style>
        .material-icons {
            position: relative;
            vertical-align: middle;
            left: 30px;
        }
     
    </style> 
</head>

<body style="">
   {% comment %} <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #ec525c">
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">BANANA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecomapp:home' %}">Trang chủ <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Danh mục</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ecomapp:mycart' %}">Giỏ hàng</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Tài khoản
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.account %}
                        <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">Tài khoản</a>
                        <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Đăng xuất</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Đăng kí</a>
                        <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Đăng nhập</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
                <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search"
                    aria-label="Search" required>
                <button class="btn my-2 my-sm-0" type="submit" style="background-color: #cce6ff">Tìm kiếm</button>
            </form>
            
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:review' %}">
                <button class="btn btn-primary" type="submit">Gửi Review</button>
            </form>
        </div>style = "background-color:#1784BE;"
    </nav>  {% endcomment %}
    <div class="container-fluid" >
    
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="{% url 'ecomapp:home' %}" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class=" font-weight-bold border px-3 mr-1" style = "background-color:white;">B</span>BANANA</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="{% url 'ecomapp:search' %}" method="GET">
                    <div class="input-group">
                        <input type="text" name="keyword" class="form-control" placeholder="Tìm kiếm mặt hàng">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <button class="fa fa-search" type="submit" style="border: none; background: #fff"></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="{% url 'ecomapp:wishlist' %}" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    {% if request.user.account == None%}
                        <span class="badge">0</span>
                    {% else %}
                        <span class="badge">{{request.user.account.users.customer.count_wishline}}</span>
                    {% endif %}
                </a>
               
                <a href="{% url 'ecomapp:mycart' %}" class="btn border" style = "background-color:white;">
                    <i class="fas fa-shopping-cart text-primary" ></i>
                    {% if request.user.account == None%}
                        <span class="badge">0</span>
                    {% else %}
                        <span class="badge">{{request.user.account.users.customer.count_item_cart}}</span>
                    {% endif %}
                </a>
            </div>
        </div>
    </div>
    <hr>
    <div class="container-fluid" >
        <div class="row border-top px-xl-5" >
            <div class="col-lg-2 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Danh mục</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                    <div class="navbar-nav w-100 overflow-hidden" style="height:auto">
                        <a href="{% url 'ecomapp:allbook' %}" class="nav-item nav-link">Sách </a>
                        <a href="{% url 'ecomapp:allelectronic' %}" class="nav-item nav-link">Đồ điện tử</a>
                        <a href="{% url 'ecomapp:allclothes' %}" class="nav-item nav-link">Quần áo</a>
                        
                    </div>
                </nav>
            </div>
            <div class="col-lg-10">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="{% url 'ecomapp:home' %}" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">B</span>BANANA</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'ecomapp:home' %}" class="nav-item nav-link">Trang chủ</a>
                            {% comment %} <a href="{% url 'ecomapp:allproducts' %}" class="nav-item nav-link">Danh mục</a> {% endcomment %}
                            <a href="{% url 'ecomapp:mycart' %}" class="nav-item nav-link">Giỏ hàng</a>

                            {% if request.user.account == None %}
                                <a class="nav-item nav-link" href="{% url 'ecomapp:customerregistration' %}">Đăng kí</a>
                                <a class="nav-item nav-link" href="{% url 'ecomapp:customerlogin' %}">Đăng nhập</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{% url 'ecomapp:customerprofile' %}">Tài khoản</a>
                                <a class="nav-item nav-link" href="{% url 'ecomapp:customerlogout' %}">Đăng xuất</a>
                            {% endif %}
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                        <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:review' %}">
                                <a type="submit" >Gửi Review</a>
                        </form>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    {% comment %} <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Checkout</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="">Home</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">Checkout</p>
            </div>
        </div>
    </div> {% endcomment %}
    <br> 

    {% block content %}
    {% endblock %}

      <!-- Footer Start -->
    <div class="container-fluid text-dark mt-5 pt-5" style="background-color:white"">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class=" font-weight-bold border px-3 mr-1" style = "background-color:white;">B</span>BANANA</h1>
                </a>
                <br>
                <p style = "font-size:20px;">Chuỗi cửa hàng số 1 Việt Nam</p>
               
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-6 mb-5" style = " text-align: center;">
                        <h5 class="font-weight-bold text-dark mb-4">Liên hệ</h5>
                        <div class="d-flex flex-column justify-content-start">
                          <div>
                            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>99 Mỗ Lao, Hà Đông, Hà Nội, Việt Nam</p>
                          </div>
                          <div>
                            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>banana@gmail.com</p>
                          </div>
                          <div>
                            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                          </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-5" >
                        <h5 class="font-weight-bold text-dark mb-4" style = " text-align: center;">Hỗ trợ</h5>
                        <div class="d-flex flex-column " style="display: flex; justify-content: center; align-items: center">
                            <a class="text-dark mb-2" href="/"><div style="width: 150px" ><i class="fa fa-angle-right mr-2"></i>Trang chủ</div></a>
                            <a class="text-dark mb-2" href=""><div style="width: 150px"><i class="fa fa-angle-right mr-2"></i>Cửa hàng</div></a>
                            <a class="text-dark mb-2" href=""><div style="width: 150px"><i class="fa fa-angle-right mr-2"></i>Chính sách</div></a>
                           
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Banana</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">Banana</a><br>
                 
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

     <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

    <script src="{%static 'js/easing.min.js' %}"></script>
    <script src="{%static 'js/owl.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{%static 'js/jqBoot.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

    

   
</body>

</html>

templates/bookproducts.html
{% extends 'base.html' %}

{% block title %}Danh mục sách{% endblock %}

{% block content %}
<div class="container-fluid" style =  "background-color:#f5f5f5;">
<div class="container "style =  "background-color:#f5f5f5;">
<div id="header-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active" style="height: 410px;">
                            {% load static %}  
                            <img class="img-fluid" src="{% static 'book2.jpg' %}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">BANANA</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Nhà sách</h3>
                                    <a href="{% url 'ecomapp:allbook' %}" class="btn btn-light py-2 px-3">Mua ngay</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item" style="height: 410px;">
                            {% load static %}  
                            <img class="img-fluid" src="{% static 'electronic.jfif' %}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">BANANA</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Đồ điện tử</h3>
                                    <a href="{% url 'ecomapp:allelectronic' %}" class="btn btn-light py-2 px-3">Mua ngay</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item" style="height: 410px;">
                            {% load static %}  
                            <img class="img-fluid" src="{% static 'clothes1.png' %}" alt="Image">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">BANANA</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Quần áo</h3>
                                    <a href="{% url 'ecomapp:allclothes' %}" class="btn btn-light py-2 px-3">Mua ngay</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-prev-icon mb-n2"></span>
                        </div>
                    </a>
                    <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-next-icon mb-n2"></span>
                        </div>
                    </a>
                </div>
 </div>
<div class="container-fluid" style = "background-color:white; padding: auto;" >
<div class="container-fluid pt-5" >
    <div class="row px-xl-5 pb-3">
        {% for p in product_list %}
            {% if p.isUpload %}
                    <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <img src="{{p.image.url}}" alt="" class="img-fluid w-100" style="height: 250px; object-fit: contain;">
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3" style = ""><a href="{% url 'ecomapp:productdetail' p.slug %}" style = "color:#2E2178;">{{p.productid.name}}</a></h6>
                                <div class=" d-flex justify-content-center">
                                    <h6>Giá: {{p.price}} VND</h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                {% comment %} <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a> {% endcomment %}
                                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Thêm vào giỏ</a>
                                {% if p in wishListItem %}
                                <a href="{% url 'ecomapp:updateWishList' p.id %}?action=rmv" class="material-icons col-md-4 "> favorite </a> 
                                {% else %}
                                <a href="{% url 'ecomapp:updateWishList' p.id %}?action=add" class="material-icons col-md-4 "> favorite_border</a> 
                                {% endif %}
                            </div>
                        </div>
                    
                    </div>
            {% endif %}
        {% endfor %}
       
    </div >
  <nav aria-label="..." >
        <ul class="pagination">
             {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}">Trước</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trước</a>
            </li>
            {% endif %}

            {% for i in product_list.paginator.page_range %}
            {% if i == product_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if product_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Sau</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Sau</a>
            </li>
            {% endif %} 
            
        </ul>
    </nav>
     
   
   
</div>
</div> 


{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}

{% block title %}Thông tin tài khoản{% endblock %}

{% block content %}
<div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 100px">
             <h1 class="font-weight-semi-bold text-uppercase mb-3" style = "font-size: 25px">Thông tin tài khoản</h1>
        </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Thông tin chi tiết</h3>
            <hr>
            <p><span class="font-weight-bold">Tên: </span> {{customer.userid.fullnameid.fullname}}</p>
            <p><span class="font-weight-bold">Tên đăng nhập: </span> {{customer.userid.accountid.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.userid.contactinfoid.email}}</p>
            <p><span class="font-weight-bold">Địa chỉ: </span> {{customer.userid.addressid.address}}</p>
            <br> 
            <a href = "{% url 'ecomapp:shippingaddresslist' customer.id %}">Chỉnh Sửa Sổ Địa Chỉ</a> 
            <br>
            <br>
            <a href = "{% url 'ecomapp:wishlist' %}">Yêu Thích</a>
            <br> 
            <br> 
            <a href = "{% url 'ecomapp:reviewlist' %}">Đánh Giá Của Tôi</a> 
            <br>
            <br>
            <a href = "{% url 'ecomapp:editprofile' customer.userid.id %}">Chỉnh Sửa Thông Tin Cá Nhân</a> 
        </div>
        <div class="col-md-8">
            <div style = "text-align:center;">
            <h3>Lịch sử đơn hàng</h3>
            </div>
            <form class="form-inline my-2 my-lg-0" action="" method="GET">
                <button class="btn my-2 my-sm-0" type="submit" style="background-color: #cce6ff">Tìm kiếm</button>
                <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search"
                    aria-label="Search" required>
            </form>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>ID</th>
                        <th>Số tiền</th>
                        <th>Ngày đặt hàng</th>
                        <th>Trạng thái</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:customerorderdetail' ord.pk %}"> #ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.time}}</td>
                        {% if ord.status == 'Order Received' %}
                            <td>Chờ xác nhận</td>
                        {% else %}
                            <td>{{ord.status}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/review.html
{% extends 'base.html' %}

{% block title %}Review{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-left">Đội Ngũ Chăm Sóc Khách Hàng.</h1>
    <h5 class="text-left">Chúng tôi luôn sẵn sàng lắng nghe ý kiến đóng góp từ bạn. Chúng tôi sẽ phản hồi trong thời gian sớm nhất.</h1>
    <hr style="height:30px">
    <div>
        <form class="row g-3" action="{% url 'ecomapp:review' %}" method="POST">
            {% csrf_token %}
            <label class="col-12"> {{ form.content.label }}:</label>
            <div class="col-12">
              {{ form.content }}
            </div>
            <div class="col-12">
              {% if request.user.account %}
                <button type="submit" class="btn btn-primary">Send</button>
              {% else %}
                <button type="submit" class="btn btn-primary" disabled>Send</button>
              {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}